version: '3.1'

services:
  db:
    image: mariadb
    restart: always
    container_name: mariaDB_bigdata
    environment:
      MYSQL_ROOT_PASSWORD: abc123.
      MYSQL_DATABASE: bigdata
      MYSQL_USER: usuario
      MYSQL_PASSWORD: abc123.
    ports:
      - 3306:3306
    volumes:
      - ./data/mariadb:/var/lib/mysql
      - ./files/mariadb:/opt/varios
    networks:
      bigdata:
        ipv4_address: 192.168.99.100

  # pentaho-server:
  #   # engadir un usuario: useradd -m -s /bin/bash pentaho
  #   # image: efja/varios:pentaho
  #   image: postgres
  #   restart: always
  #   container_name: pentahosvr_bigdata
  #   build: ./build/ph
  #   environment:
  #     POSTGRES_PASSWORD: abc123.
  #   volumes:
  #     # - ./data/pentaho:/data
  #     - ./app:/opt/pentaho-install
  #   ports:
  #     - "8009:8009"
  #     - "8080:8080"
  #     - "8081:8080"
  #     - "9001:9001"
  #     - "11001:11001"
  #     - "5432:5432"
  #   networks:
  #     bigdata:
  #       ipv4_address: 192.168.99.101

  # pentaho-ce-server:
  #   image: zhicwu/biserver-ce
  #   restart: always
  #   container_name: pentahosvr_ce_bigdata
  #   environment:
  #     SERVER_PASSWD: 'abc123.'
  #     DB_HOST: pentahobi-ce
  #     DB_PORT: 3306
  #     DB_USER: usuario
  #     DB_PASSWD: 'abc123.'
  #   volumes:
  #     # - ./data/pentaho:/data
  #     - ./app:/opt/pentaho
  #   ports:
  #     - "8089:8080"
  #   networks:
  #     bigdata:
  #       ipv4_address: 192.168.99.102

  webspoon:
    image: hiromuhota/webspoon
    restart: always
    container_name: webspoon_bigdata
    environment:
      - "JAVA_OPTS=-Xms1024m -Xmx2048m"
    ports:
      - "8082:8080"
    volumes:
      - ./data/spoon/lib/mariadb-java-client-2.7.4.jar:/usr/local/tomcat/lib/mariadb-java-client-2.7.4.jar
      - ./files/spoon:/home/tomcat/.kettle/data/compartido
    networks:
      bigdata:
        ipv4_address: 192.168.99.103

  jupyter:
    image: jupyter/base-notebook:latest
    container_name: jupyter_bigdata
    ports:
        - "8891:8888"
    command: "start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''"
    user: root
    environment:
      NB_USER: usuario
      NB_UID: 1008
      NB_GID: 1011
      CHOWN_HOME: 'yes'
      CHOWN_HOME_OPTS: -R
    networks:
      bigdata:
        ipv4_address: 192.168.99.105

networks:
  bigdata:
    name: bigdata
    driver: bridge
    driver_opts:
     com.docker.network.bridge.name: bigdata
    ipam:
     config:
       - subnet: 192.168.99.0/24
